language: node_js
sudo: false
node_js:
  - 4.1
  - 4.0
  - 0.12
env:
  - NODE_ENV=test
notifications:
  email:
    on_success: never
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coveralls
